### ISSUE TITLE
Regression: snapcraft "apt" package-repositories feature fails in destructive mode

### ISSUE THREAD

**Issue by basak** [snapcore/snapcraft#4225] opened 2023-06-20 12:25 UTC
### Bug Description

See #4224 for the background.

I tried dropping subkey generation to work around the issue (it's gpg's interactive default, but not needed for this case). But then I got a further error: `[Errno 13] Permission denied: '/etc/apt/keyrings'`. This is running snapcraft in destructive mode. The "apt" package-repositories used to work fine, but has now regressed. Perhaps snapcraft used to use sudo, but now doesn't?

### To Reproduce

In a Focal lxd container, running as the ubuntu user (eg. `lxc launch ubuntu:focal test-container && lxc shell test-container` and then `login -f ubuntu`):

```
git clone https://git.launchpad.net/git-ubuntu
git checkout 8f0d8e5
```

Modify snap.sh as follows:

```
diff --git a/snap.sh b/snap.sh
index 260a968..7ca6355 100644
--- a/snap.sh
+++ b/snap.sh
@@ -58,8 +58,6 @@ gpg --batch --gen-key <<EOF
 %no-protection
 Key-Type:1
 Key-Length:2048
-Subkey-Type:1
-Subkey-Length:2048
 Name-Real: git-ubuntu build script apt repo
 Name-Email: ubuntu-devel-discuss@lists.ubuntu.com
 Expire-Date:0
```

Then run:

`sh snap.sh`

### Environment

Snapcraft is in destructive mode inside a lxd container.

### snapcraft.yaml

```shell
See https://git.launchpad.net/git-ubuntu/tree/snap/snapcraft.yaml although note that snap.sh modifies it slightly to work around LP: #1918968. See that script for details.
```

### Relevant log output

```shell
Sorry, an error occurred in Snapcraft:
[Errno 13] Permission denied: '/etc/apt/keyrings'
```

**Comment by basak** [comment] 2023-06-20 13:35
Running `snapcraft --destructive-mode` with sudo works around the issue. git-ubuntu MP: https://code.launchpad.net/~racb/git-ubuntu/+git/usd-importer/+merge/445060

**Comment by basak** [comment] 2023-06-20 13:57
https://paste.ubuntu.com/p/THSJ9Tk5Pw/ for the entire run of snap.sh, including the call to snapcraft.

/tmp/tmp6zsj42t4/trace.txt in https://paste.ubuntu.com/p/7CBJQPdC2m/

**Comment by tigarmo** [comment] 2023-06-21 11:58
Thanks. It's failing to create `/etc/apt/keyrings` in the container, but it's surprising to me that this used to work. The previous code put the key in `/etc/apt/trusted.gpg.d/snapcraft.gpg`, which should have the same permissions/ownership. Which user are you running this as (inside the container)?

**Comment by basak** [comment] 2023-06-21 12:03
Just the ubuntu user. It's possible I'm mistaken, but I just checked the Jenkins job and that's what it looks like to me.

Could you give me an appropriate snap revision of the snapcraft before the change, please, and I could check previous behaviour to see if I can reproduce it working?

**Comment by sergiusens** [comment] 2023-06-21 12:49
Not sure what architecture you are looking for, but here's current stable and previous stable for all arches

```
sergiusens@imladris:~$ snapcraft list-revisions snapcraft | grep latest/stable
9367    2023-06-14T11:58:21Z  riscv64   7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9366    2023-06-14T09:26:15Z  ppc64el   7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9365    2023-06-14T09:26:14Z  armhf     7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9364    2023-06-14T09:24:15Z  arm64     7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9363    2023-06-14T09:24:13Z  s390x     7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9362    2023-06-14T09:17:16Z  amd64     7.4.3                     7.x/candidate,7.x/stable*,latest/candidate,latest/stable*
9210    2023-05-18T18:39:22Z  riscv64   7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
9209    2023-05-18T16:19:15Z  armhf     7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
9207    2023-05-18T16:03:19Z  ppc64el   7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
9204    2023-05-18T15:57:13Z  s390x     7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
9203    2023-05-18T15:54:27Z  arm64     7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
9201    2023-05-18T15:52:24Z  amd64     7.3.2                     7.x/candidate,7.x/stable,latest/candidate,latest/stable
```

**Comment by basak** [comment] 2023-06-21 13:38
Thanks! I did some manual testing, and found that indeed this is a regression moving from r9201 to r9362, using the `ubuntu` user. With r9201 snapcraft works fine. With r9362 I get the `[Errno 13] Permission denied: '/etc/apt/keyrings'` error.

Exact steps to reproduce:

```
lxc launch ubuntu:focal rbasak-gpg-apt
lxc exec rbasak-gpg-apt bash
login -f ubuntu
git clone https://git.launchpad.net/git-ubuntu
cd git-ubuntu
git checkout 1209559
vi snap.sh
# replace: sudo snap install --classic snapcraft
# with: sudo snap install --classic --revision 9201 snapcraft
whoami
sh snap.sh
```
The above works successfully. Note that it runs as the `ubuntu` user. If you follow the exact same steps except to use `--revision 9362` instead, then it fails with `[Errno 13] Permission denied: '/etc/apt/keyrings'`.

**Comment by tigarmo** [comment] 2023-06-21 14:14
@basak thanks a lot for the repro script! Extremely helpful.
This is a `core20` snap and it looks like Snapcraft 7.3.2 [did use "sudo"](https://github.com/snapcore/snapcraft/blob/7.3.2/snapcraft_legacy/internal/repo/apt_key_manager.py#L123) exactly to handle destructive mode for that core, so that's the source of the regression.

**Comment by tigarmo** [comment] 2023-07-14 21:45
@basak we'll be putting out Snapcraft 7.5 soon which will revert these package-repositories regressions (the need for explicit `sudo`, and the subkeys restriction) for core18 and core20. I tested your script (the original one without the modifications from the regressions) on a dev version and things seem to be back to normal.

**Comment by basak** [comment] 2023-07-15 10:37
Thank you!

**Comment by basak** [comment] 2023-08-21 11:21
This works against 7.5.2 again, thanks! I reverted the workaround and got a CI passed, and merged it.

**Comment by tigarmo** [comment] 2023-08-21 11:30
Thanks for the confirmation! I'll close this then.

**Closed by tigarmo** 2023-08-21 11:30 UTC
Labels: Bug
